version: '3'

services:
  app:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # This path is hardcoded many places...
      - "./data/config:/srv/avss/appdata/etc"

      - "./data/letsencrypt:/etc/letsencrypt"
    environment:
      # Set DOMAIN=... and MAIL=... in a file called ".env"
      DOMAIN: "${DOMAIN}"
      MAIL: "${MAIL}"
