version: '3'

services:
  app:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./data/config:/app/config"
      - "./data/letsencrypt:/etc/letsencrypt"
    environment:
      DOMAIN: ""
      MAIL: ""
